name: example
description: "Following Wind example project"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  followind:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

dependency_overrides:
  followind:
    path: ../

flutter:
  uses-material-design: true
